// DONE
export const TOURNAMENT_DATA_REQUEST = 'TOURNAMENT_DATA_REQUEST';
export const TOURNAMENT_DATA_SUCCESS = 'TOURNAMENT_DATA_SUCCESS';
export const TOURNAMENT_DATA_FAIL = 'TOURNAMENT_DATA_FAIL';
